// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.lintips.inventario.domain;

import com.lintips.inventario.domain.ProductoDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect ProductoDataOnDemand_Roo_Configurable {
    
    declare @type: ProductoDataOnDemand: @Configurable;
    
}
